version: "3"
services:
    andon:
        image: node:12-alpine
        container_name: andon
        working_dir: /andon/
        env_file:
            - ./.env
        command: yarn dev
        ports:
            - 8000:8000
        volumes:
            - ./:/andon/:consistent
    db:
        image: postgres:12-alpine
        container_name: db
        env_file:
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - ./db_data/:/var/lib/postgresql/data/:consistent
networks:
    default:
        external:
            name: ds_network