const WARNING_TYPE = {
	WARN: 'WARN',
	ALERT: 'ALERT',
};

const WARNING_REASON = {
	MATERIAL: 'MATERIAL',
	PESSOAL: 'PESSOAL',
	PROJETO: 'PROJETO',
	SEGURANÇA: 'SEGURANÇA',
};

module.exports = {
	WARNING_TYPE,
	WARNING_REASON,
};